// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC07Rbb9Xyws4y7lBbUhqhosZvqGIE7Bhc',
    appId: '1:347930300612:web:7f08dcf8262968d915f991',
    messagingSenderId: '347930300612',
    projectId: 'teia-f652a',
    authDomain: 'teia-f652a.firebaseapp.com',
    databaseURL: 'https://teia-f652a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teia-f652a.appspot.com',
    measurementId: 'G-CXQTQ1DVYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFV3gf4hTOdojsyxXVvWoErXSTiCvUagA',
    appId: '1:347930300612:android:0431b3e232dbec6915f991',
    messagingSenderId: '347930300612',
    projectId: 'teia-f652a',
    databaseURL: 'https://teia-f652a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teia-f652a.appspot.com',
  );
}
